language: android
android:
  components:
    - build-tools-26.0.1
    - android-26
  licences:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'
